### ISSUE TITLE
THREE.js viewer example missing face colors

### ISSUE THREAD

**Issue by Glavin001** [kovacsv/occt-import-js#15]
THREE.js viewer example: https://github.com/kovacsv/occt-import-js/blob/main/examples/three_viewer.html#L28-L64

I've added a working (so far in my tests) `face_colors`  implementation to this Codesandbox: https://codesandbox.io/s/convert-step-file-to-glb-with-three-js-occt-import-js-v0-3-5hk66o?file=/src/StepLoader.js

- Does my implementation look to be on the right track?
- Would you like a Pull Request updating the THREE.js viewer example?

**Comment by kovacsv** [comment]
I prefer to use [material groups](https://threejs.org/docs/#api/en/core/BufferGeometry.groups) instead of vertex colors, but both can work. A Pull Request is always welcome!

**Comment by Glavin001** [comment]
Good to know, thanks! I'm relatively new to Threejs and learning these concerns this week. Appreciate your feedback.

I've been trying to learn from https://github.com/kovacsv/Online3DViewer/blob/master/source/engine/import/importerocct.js
Could more of the code from Online3DViewer be brought into this library, such as color support, or is this separation intentional?

Thanks for creating this awesome library! 🎉

**Comment by kovacsv** [comment]
The separation is intentional, actually the dependency is reversed: [Online3DViewer](https://github.com/kovacsv/Online3DViewer) uses [occt-import-js](https://github.com/kovacsv/occt-import-js) under the hood. This library should be independent from Online 3D Viewer to make it usable more widely.

**Comment by hyfbeetle** [comment]
How to show face colors with this library? 
Will it be done in near future?  Thanks very much.

**Comment by kovacsv** [comment]
I've added face color handling to the example:
https://github.com/kovacsv/occt-import-js/blob/main/examples/three_viewer.html#L62-L89

**Comment by hyfbeetle** [comment]
Appreciate your feedback, thanks very much!
Problem is resultMesh.face_colors is undefined, file "dm1-id-214.stp" from test directory has face colors, but cann't display.
