### ISSUE TITLE
Compare step files, visually.

### ISSUE THREAD

**Issue by leoheck** [kovacsv/occt-import-js#16]
Hi, first of all, thanks for creating and sharing this nice project. 

I am constantly looking for a way to compare step files like this example found on Google.

![image](https://user-images.githubusercontent.com/1277920/199258085-7138223f-7566-4808-8d76-397f7cbb4643.png)
https://www.glovius.com/blog/compare-3d-cad-files/

This tool is promising to have such a feature. 
So, I would like to ask if `occt-import-js` does have something that allows or assists to do this kind of operation.

Thanks in advance.

**Comment by kovacsv** [comment]
This kind of functionality is out of scope for this library. The goal for this library is to convert traditional CAD formats to a bunch of triangles.

**Comment by leoheck** [comment]
I see, thanks for the answer. 
Do you have an idea of any tool or library that does what I am looking for?
