### ISSUE TITLE
occt-import-js gltf output

### ISSUE THREAD

**Issue by ginolos** [kovacsv/occt-import-js#18]
Hello Kovacsv, 
Thanks for building such an awesome tool. 
Is there any way to export as gltf or convert the output to gltf? The JSON format is no longer supported by three js.

**Comment by kovacsv** [comment]
glTF export is out of the scope of this project, but you can find a function that converts the resulting json to three.js format in [this fiddle](https://jsfiddle.net/kovacsv/rzhq9gxj). See the `LoadGeometry` function.

**Comment by ginolos** [comment]
Thank you!
