### ISSUE TITLE
Export assembly back to step file

### ISSUE THREAD

**Issue by longhan** [kovacsv/occt-import-js#21]
Hi kovacsv,

Using occt-import-js. I can read multiple .stp file and loaded into threejs screen.

Can occt-import-js export back to .stp file as a whole assembly?

Thank in advance! LH

**Comment by kovacsv** [comment]
Hey,

The short answer is no.

The longer answer is that the library converts the boundary representation of the step model to a bunch of triangles. It means that all geometrical information stored in the file will be lost during the process, so I don't think it would make much sense to write the tesselated model back to a step file.

**Comment by longhan** [comment]
Thanks!
