### ISSUE TITLE
emscripten: enable lto for reducing binary size

### ISSUE THREAD

**Issue by kzhsw** [kovacsv/occt-import-js#27]
<https://emscripten.org/docs/optimizing/Optimizing-Code.html#lto>

**Comment by kovacsv** [comment]
Thanks for the suggestion! Have you tried it? How much did it help?

**Comment by kzhsw** [comment]
> Thanks for the suggestion! Have you tried it? How much did it help?

the original dist
![the original dist](https://github.com/kovacsv/occt-import-js/assets/120431159/77fb67ac-3029-4eb1-b35a-3e293136bada)

lto build
![lto build](https://github.com/kovacsv/occt-import-js/assets/120431159/c5ed7baf-9f9f-477b-a63a-93372d62b233)

**Comment by kovacsv** [comment]
By using `wasm-exceptions` the file size is already lower, and with this setup the `lto` flag didn't have any visible effect on file size.
