### ISSUE TITLE
emscripten: use wasm-exceptions for better performance

### ISSUE THREAD

**Issue by kzhsw** [kovacsv/occt-import-js#29]
Using this project to parse a large (~80MB) stp file, I waited for more 4 hours but it wouldn't finish, when I pause the script in devtools, it stops at some js glue code generated by emscripten, which is supposed to be exception handling.
The [docs](https://emscripten.org/docs/porting/exceptions.html#webassembly-exception-handling-based-support) said wasm-exceptions should be faster, but I failed to compile it.
The same model took about 2 minutes to be converted to gltf using [mayo](https://github.com/fougue/mayo), which is a native app using the same OpenCascade to handle stp files.
I had tried [foxtrot](https://github.com/Formlabs/foxtrot) on browser, but it just failed.

Other useful links:
* [WebAssembly exception handling proposal](https://github.com/WebAssembly/exception-handling/blob/master/proposals/exception-handling/Exceptions.md)
* https://github.com/llvm/llvm-project/issues/62877
* https://webassembly.org/roadmap/

**Comment by longhan** [comment]
Hello,

Can you please share your .stp?

**Comment by kzhsw** [comment]
> Hello,
> 
> Can you please share your .stp?

No, it's commercial stuff. During a quick look of OpenCascade code, I found that c++ exceptions are widely used in it, so using wasm-exceptions should improve the overall performance by reducing wasm-js calls, not limited to specify model.

**Comment by kovacsv** [comment]
@kzhsw I managed to compile the library with `-fwasm-exceptions`, tests are running fine, and the binary is even smaller than before. Now I would like to test with your model, could you please share it with me somehow?

**Comment by kzhsw** [comment]
> @kzhsw I managed to compile the library with `-fwasm-exceptions`, tests are running fine, and the binary is even smaller than before. Now I would like to test with your model, could you please share it with me somehow?

Thank you for this, I'll try to find a model that can be uploaded here. Could you upload the compiled binary here, or benchmark it with some smaller models?

**Comment by kovacsv** [comment]
Some measurements for files I got at hand. It's definitely faster, but I guess the difference depends on the number of exceptions coming from the import.

| File Name  | File Size | Old version | New version |
|---|---|---|---|
| as1_pe_203.stp  | 0.2Mb | 0.671s | 0.307s |
| GPT-05-BL.stp  | 0.5Mb | 1.650s | 0.956s |
| MDrive23Plus.stp  | 3.2Mb | 9.127s | 4.999s |
| MD34AC_single.stp  | 10.9Mb | 26.869s | 13.233s |
| Product1TamMontaj.stp  | 12.2Mb | 40.710s | 20.810s |

**Comment by kovacsv** [comment]
@kzhsw even if it doesn't solve your problem it's definitely better than it was before, so I committed the new compiled version. Please check it with your file.

**Comment by kzhsw** [comment]
Thank you for this great work! Also note for best browser compatibility, both version should be compiled, and load the supported version based on browser version check or [wasm-feature-detect](https://www.npmjs.com/package/wasm-feature-detect).
BTW, it would be better to upload compiled wasm dist to [releases](https://github.com/kovacsv/occt-import-js/releases), allowing devs to have a faster checkout.

**Comment by kovacsv** [comment]
Browsers and node.js supports this feature for more than a year, I think it's fine to have only the new version.
