### ISSUE TITLE
Request for Help

### ISSUE THREAD

**Issue by zhangcanfeng612** [kovacsv/occt-import-js#31]
Hello, 
could you please guide me on how to set up a local development environment? 
I've been struggling with this for quite a while.

**Comment by zhangcanfeng612** [comment]
I am a front-end developer. Currently, I have successfully compiled OCCT, but I am unable to debug the code.

**Comment by kovacsv** [comment]
What part of the code would you like to debug? The C++ or the JavaScript?

**Comment by zhangcanfeng612** [comment]
Thank you for your response. I would like to debug C++ code, 
and I have a question: Can I only generate a source map for debugging in the browser?

We have a time difference, so our responses may be a bit slow. Please accept our apologies for any inconvenience caused.

**Comment by kovacsv** [comment]
It depends on your setup, on Windows you need to do the following steps:
1. Install Visual Studio 2022.
2. Install CMake.
3. Generate the project with CMake by running the following command from the root of the repository:
```
cmake -B build -G "Visual Studio 17 2022" .
```
4. Open the generated solution (`build/OcctImportJS.sln`), compile and run the test application.

On other platforms it's similar, just replace Visual Studio with the native environment on the platform.

**Comment by zhangcanfeng612** [comment]
Thank you for your guidance, I will try my best!!!!

**Comment by zhangcanfeng612** [comment]
Hello, Can I obtain the lines and points Array representing in a similar manner as obtaining brep_faces (an array representing the faces of the source b-rep)?

I want to implement geometry picking functionality in the browser (Three.js).
