### ISSUE TITLE
ReadStepFile function takes a long time to read STEP file

### ISSUE THREAD

**Issue by omkarap55** [kovacsv/occt-import-js#33]
Hi, I have observed that ReadStepFile function takes a long time to read STEP files (Took more than 3 mins on my machine to load 25mb STEP file).
Is there any way to reduce this loading time?

**Comment by kovacsv** [comment]
The speed is not dependent on the file size, but more like the complexity of the model. Usually the triangulation takes the most time of the loading process. You can set the `linearDeflection` and `angularDeflection` parameters to modify the level of segmentation, and that should make it faster.

See the documentation for details:
https://github.com/kovacsv/occt-import-js
