### ISSUE TITLE
Use occt-import-js report an error

### ISSUE THREAD

**Issue by littleBelle** [kovacsv/occt-import-js#4]
When i install occt-import-js，and i use it like this：
![image](https://user-images.githubusercontent.com/53242999/170236795-a51f3240-1824-4507-ab84-37430264862a.png)
then the console report an error like this：
![image](https://user-images.githubusercontent.com/53242999/170237019-fa64e972-1486-495d-ab78-ac6922506e2b.png)
Please give me a help！thanks！

**Comment by kovacsv** [comment]
I recommend using the library from browser like in this example:
https://github.com/kovacsv/occt-import-js/blob/main/examples/browser_step.html

**Comment by littleBelle** [comment]
![image](https://user-images.githubusercontent.com/53242999/171318691-627e082f-7138-438e-9ae2-446d04c8ac75.png)
But I need use as a node.js module
would you give me some help? thanks a lot!

**Comment by littleBelle** [comment]
![image](https://user-images.githubusercontent.com/53242999/171318691-627e082f-7138-438e-9ae2-446d04c8ac75.png)
But I need use as a node.js module
would you give me some help? thanks a lot!

**Comment by kovacsv** [comment]
Close this because of inactivity.
