### ISSUE TITLE
Surfaces are occasionally missed.

### ISSUE THREAD

**Issue by nathanielfernandes99** [kovacsv/occt-import-js#42]
Some surfaces are not meshed. See
[example.zip](https://github.com/user-attachments/files/16653283/example.zip). When opening it inside CAD software, all surfaces are displayed.

**Comment by chriskuech** [comment]
I'm facing this issue as well. Any idea what's happening with the dropped faces?

**Comment by chriskuech** [comment]
I am also not able to reproduce the issue in https://3dviewer.net/

**Comment by nathanielfernandes99** [comment]
I cant figure it out, it only seems to happen sometimes with cone surfaces.

**Comment by nathanielfernandes99** [comment]
The test step i attached has the conical surface missing when using 3dviewer.net

**Comment by nathanielfernandes99** [comment]
Okay great!

Let me know when you think you have it fixed.

**Comment by kovacsv** [comment]
Fixed in the latest release.
