### ISSUE TITLE
Requesting for Help. Loaded STEP file not visible.

### ISSUE THREAD

**Issue by VadimKhismatov** [kovacsv/occt-import-js#49]
Hello. I'm trying this library to see if I can use it in my project. I used the code from the jsfiddle-example, slightly changing it. With the file "as1_pe_203.stp" everything works, but when I load my file, the 3D model does not appear, there are no errors in the console. I converted **.step** to **.stp**, still not working. Can you help me understand what the problem is? 

**[Stackblitz example](https://stackblitz.com/edit/vitejs-vite-agbkez?file=main.js)**
My files is in **public** folder: **example1.step, example1.stp, example2.step**

**Comment by 123Wampir** [comment]
Your model is too small. Change the camera position
`camera.position.set(5.0, 1.0, 1.0);` at line 61

**Comment by VadimKhismatov** [comment]
@123Wampir Thank you for your help.
