### ISSUE TITLE
Add parameter to define mesh triangulation quality

### ISSUE THREAD

**Issue by ELIONET** [kovacsv/occt-import-js#5]
Hello,

I was wondering if there was a way to specify any parameter for the STEP -> triangulated mesh conversion ? I was mainly thinking of parameters affecting the quality of the resulting mesh.

**Comment by kovacsv** [comment]
It's not available at the moment.

**Comment by trusktr** [comment]
Oh, interesting, I didn't know anything about STEP, but this issue hints that it sort of like 3D vectors.

**Comment by kovacsv** [comment]
Triangulation parameters are available in version `0.0.14`.
