### ISSUE TITLE
Reusable mesh geometries

### ISSUE THREAD

**Issue by ThaiLe-gt** [kovacsv/occt-import-js#9]
Hello Kovacsv!!!

Thank you for your great library!!!
I used your library in Node JS successfully.
But I have faced some issues:
 - The STP files which over >50MB can not display in Three js (Please check my file attached below).
 - The mesh geometries that have the same properties are not reusable in the result, which will affect the performance for loading and importing.
[Powder.zip](https://github.com/kovacsv/occt-import-js/files/9215177/Powder.zip)

**Comment by GitHubDragonFly** [comment]
Just to pitch in, this seems to be choking the function `occt.ReadStepFile( fileBuffer )` since the `fileBuffer` appears to be an array of 73+ million in length.

**Comment by kovacsv** [comment]
I think it would be also solved by #5. The basic problem here is that the built-in triangulation logic can end up with really large meshes, so it would be great to make users able to define the quality from the outside.

**Comment by kovacsv** [comment]
Triangulation parameters are available in version `0.0.14`.
